# Changes here will be overwritten by Copier
_commit: 0.14.2
_src_path: gh:bhklab/bhklab-project-template
author_email: bhklab.jamesbannon@gmail.com
author_full_name: James Bannon
github_username: jbannon
has_additional_authors: false
project_description: Combining mutation and genomics for clinical outcome prediction
project_name: Glioma Radiogenomics
project_slug: glioma-radiogenomics
publish_to_github: true
python_version: '3.12'
repo_location: bhklab
